### PR TITLE
hotfix/TR-1535/choice-container-remains-expanded

### PR DESCRIPTION
**Pull request by marpesia**
Backport of [TR-1535](https://oat-sa.atlassian.net/browse/TR-1535)

**Description:**
Hide by default the tool 'answer-eliminator because the SVG from the tool is creating extra space on loading and pushing choice interaction box on resizing function.

**Changes:**

- CSS hide property

**How to check:**

- Test attached to the ticket.
- Use a low 3G network connection to reproduce

**Requires:**

- https://github.com/oat-sa/tao-test-runner-qti-fe/pull/419

### CODE REVIEW

**Review by jsconan — APPROVED** [review]
looks good

**Review by jsconan — CHANGES_REQUESTED** [review]
Since this change is for a sprint prior to 149 you still need to bump the version in the manifest file.

See: https://github.com/oat-sa/extension-tao-testqti/blob/release-39.4.1.7/manifest.php#L53

**Review by jsconan — APPROVED** [review]
looks good

**Review by meefox — APPROVED** [review]
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

**Pull request merged**
