### PR TITLE
fix/TR-1251/offline-behavior-modal-feedback-item

### PR DESCRIPTION
**Pull request by marpesia**
Relative to [TR-1251](https://oat-sa.atlassian.net/browse/TR-1251)

Translation of :
English
You are encountering a prolonged connectivity loss.

French
Vous rencontrez une perte de connectivité prolongée.

Dutch
Je hebt te maken met een langdurig verbindingsprobleem.

German
Die Verbindung ist seit längerer Zeit unterbrochen. Klicken Sie, um neu zu laden.

-----

English
Please wait while we try to restore the connection."

French
Veuillez attendre pendant que nous essayons de restaurer la connexion.

Dutch
Gelieve te wachten terwijl we de verbinding proberen te herstellen."

German
Haben Sie bitte einen Moment, wir versuchen die Verbindung wiederherzustellen.

### CODE REVIEW

**Review by jsconan — COMMENTED** [review]
It works fine.
However, are you sure the existing translations should be updated?
It looks like a customer specific need applied to a shared component.
I'd rather suggest applying the non existing translations, and/or align the existing ones (ex: the missing translations in fr-CA should be aligned with the existing one on fr-FR). And place the specific translations into the customer's extension. Unless, this was a product decision to update the texts on the shared version.

**Review by btamas — APPROVED** [review]
It works, but +1 to JS's concern.
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

**Review by meefox — APPROVED** [review]
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [ ] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

**Review by jsconan — APPROVED** [review]
Looks good.
Just a small remark about the PR description: please avoid mentioning private references in public repo. Moreover, the right way is to mention the dependencies from the consumer PR only, not the opposite.

To be more explicit, assuming we have A depending on B, we can:
- declare B as being a dependency in A
- but not declare A as requiring B in B

To give you a picture, a component does not have to know where it is used, but a container needs to know which component it needs.

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

**Review by lecosson — APPROVED** [review]
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

**Review by btamas — APPROVED** [review]
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

**Pull request merged**
