### PR TITLE
Save test exit code before closing the session

### PR DESCRIPTION
**Pull request by hutnikau**

### CODE REVIEW

**Comment by ssipasseuth** [comment]
testing instruction by Oleg : 
>I changed the way of saving exit codes. To test it you can create test containing two sections (first of them should be with timer). You have to expire first section, and finish normally second.

>In the results you will see following codes:

>703 for first section
>700 for second section
>C for test


  
>Also if you set exitButton parameter in the testRunner.conf.php config to true you will be able to terminate test execution by pressing exit button. In this case you will see following codes in results:
>IC for test  
>701 fot section

**Comment by ssipasseuth** [comment]
However, I cannot get the 700 for some reason. That explains why I cannot merge this PR yet.
Is this supposed to be merged to the develop branch or to the more specific act-test-patch ?

**Comment by hutnikau** [comment]
Sam could not get the code because of his `testRunner` configuration. I updated the code in order to be able save exit code regardless on configuration parameters.

@jsconan please review this pull request as soon as possible because i have a lot of urgent tasks related to this feature.

Thanks.

**Comment by jsconan** [comment]
Ok, I get the 704, 703, 700 and C codes, and also 701 and IC.

**Pull request merged**
