### PR TITLE
check if item session given

### PR DESCRIPTION
**Pull request by hutnikau**

### CODE REVIEW

**Comment by krampstudio** [comment]
could you please elaborate

**Comment by hutnikau** [comment]
When delivery execution paused/terminated from proctoring interface user gets error after click on  `next` button instead of appropriate message because result object has no `itemSession` property.

**Comment by krampstudio** [comment]
In that case, in addition the server's `move` should return 
```js
{ 
    success: false,
   code: 0,
   type: 'TestState',
   message: __('Session paused')
 }
```

**Comment by hutnikau** [comment]
But move request even never be called without this fix.

**Pull request merged**
