### PR TITLE
Feature/tr 33/rtl bottom action bar

### PR DESCRIPTION
**Pull request by lecosson**
**Related to:** https://oat-sa.atlassian.net/browse/TR-33

**Changes:**
- qt-fe package version changed

**How to check:**
- see required PR description

**Notes:**
- changes moved from [another PR](https://github.com/oat-sa/extension-tao-testqti/pull/2035) to change magnitude from `fix` to `feature` 
- `package.json` must be changed after release of required package

**Requires:**
 - [ ] https://github.com/oat-sa/tao-test-runner-qti-fe/pull/405

### CODE REVIEW

**Review by marpesia — APPROVED** [review]
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x]  Commits messages are meaningful
- [x]  Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

**Review by jsconan — CHANGES_REQUESTED** [review]
Mostly good, but I found issues with the "hide review" and the "end test" icons which should also be reverted.
image
image

image

Could you also check other navigation buttons, like the Next section button?

Don't forget to update the CSS once the companion PR will get fixed

**Review by jsconan — COMMENTED** [review]
Looks ok, but only once  the SCSS got compiled again. Please update the PR

**Review by jsconan — APPROVED** [review]
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

**Pull request merged**
