### PR TITLE
use slash instead of directory separator constant

### PR DESCRIPTION
**Pull request by hutnikau**

### CODE REVIEW

**Comment by zagovorichev** [comment]
@siwane Try to install TAO from dev-develop

**Comment by hutnikau** [comment]
Any updates related to this PR? I still cannot install Tao on Windows.

**Comment by siwane** [comment]
I just test it, could u add a version update please

**Comment by siwane** [comment]
I just test it, could u add a version update please

**Comment by chazotte** [comment]
Without this change, I confirm that TAO installation fails on Windows:
A fatal error occured during installation: No QTI-XML test file found.

**Pull request merged**
