### PR TITLE
Tao 871 exit button

### PR DESCRIPTION
**Pull request by ssipasseuth**

### CODE REVIEW

**Comment by bugalot** [comment]
Not already merged but code review. Excellent use of IdentifierCollection->contains() :+1:

**Comment by ssipasseuth** [comment]
Oops I realized that I forgot to change the name of the category, please wait a few minutes.

**Comment by ssipasseuth** [comment]
Done.
You may test this PR with the sample test attached to https://oat-sa.atlassian.net/browse/TAO-871.

**Comment by bugalot** [comment]
Thanks Sam I am currently testing your PR.

**Comment by bugalot** [comment]
Works fine for me @ssipasseuth !

**Comment by ssipasseuth** [comment]
Great, thanks !

**Pull request merged**
