### PR TITLE
feat: add configuration variable to omit pause message

### PR DESCRIPTION
**Pull request by yohanlaborda**
# [TR-2500](https://oat-sa.atlassian.net/browse/TR-2500)

## Changelog
- feat: add configuration variable to omit pause message

## How to test
1. Go to the [kitchen](http://test-tr-bosa.playground.kitchen.it.taocloud.org:41921)
2. Run a proctored assessment as a test taker
3. Authorize the assessment as a proctor
4. Pause the assessment as the test taker
5. Pause the assessment as the test taker
6. Observe that it does not show the message to the test-taker and reload the page

### CODE REVIEW

**Review by augustas — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

**Comment by poyuki** [comment]
Probably this PR should contain front-end packges  with PR https://github.com/oat-sa/tao-test-runner-qti-fe/pull/460? @augustas i understand it correctly?

**Comment by augustas** [comment]
@poyuki, if the linked FE pull request would be merged/released, then yes, but if we want to close this ticket in current sprint then it can stay separate.

**Review by poyuki — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

**Review by augustas — APPROVED** [review]

**Pull request merged**
