### PR TITLE
Fix rubric block editor

### PR DESCRIPTION
**Pull request by krampstudio**
- replace item's html editor by only ckeditor
 - image management is still not supported

### CODE REVIEW

**Comment by ssipasseuth** [comment]
It works fine !

However I have a few comments on the style of the rubric block editor :
* the list element has a weird background (that disappear in the delivery)
* the section of rubricBlock is marked in red, looks a bit like an error (won't a lighter $info blue be better?)
* after reloading the test, previously created rubricBlock are hidden by default (I thought that my rubric block didn't save for a while)

If it is not too complicated, is it worth considering these changes ?

**Comment by bugalot** [comment]
If you need any help to find out why it "disappears in the delivery", just let me know!

**Comment by ssipasseuth** [comment]
Sorry, I meant the background color only is not there in the delivery (although it is in the authoring) :)
So I believe it is just a css issue.

**Comment by bugalot** [comment]
Thanks for the info :) :+1:

**Comment by krampstudio** [comment]
No it's not difficult to change. I'll do it.

**Comment by bugalot** [comment]
It's working pretty well guys! The only glitch is on my side were the base.css stylesheets for rubric blocks does not really align with what the authoring tool shows.

I will make some changes on the delivery side to make it more homogeneous.

Cheers,
Jérôme

**Pull request merged**
