### PR TITLE
fix: TR-857 update test-runner-qti-fe package

### PR DESCRIPTION
**Pull request by lecosson**
**Related to:** https://oat-sa.atlassian.net/browse/TR-857

**Changes:**
- package test-runner-qti-fe updated

**How to check:**
- [check related PR description](https://github.com/oat-sa/tao-test-runner-qti-fe/pull/400)

**Requires:**
 - [ ] https://github.com/oat-sa/tao-test-runner-qti-fe/pull/400

### CODE REVIEW

**Review by marpesia — APPROVED** [review]
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x]  Commits messages are meaningful
- [x]  Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

**Review by meefox — APPROVED** [review]
Technical PR

**Review by jsconan — CHANGES_REQUESTED** [review]
As expressed in the companion PR:
The change is ok regarding the connectivity message and the progress box. However, the timer is not properly displayed in RTL.

Compare:
image
image

**Review by jsconan — COMMENTED** [review]
It works fine, but only once the SCSS got compiled.
Could you commit the updated CSS files?

**Review by jsconan — APPROVED** [review]
Looks good.

image

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

**Pull request merged**
