### PR TITLE
feat: added text-to-speach preset + feature flag

### PR DESCRIPTION
**Pull request by pnal**
https://oat-sa.atlassian.net/browse/AUT-1085

### CODE REVIEW

**Review by andreluizmachado — CHANGES_REQUESTED** [review]
Nice Job! I've just written a few questions.

**Review by andreluizmachado — CHANGES_REQUESTED** [review]

**Review by bartlomiejmarszal — COMMENTED** [review]
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

**Review by bartlomiejmarszal — APPROVED** [review]
LGTM

**Review by hectoras — APPROVED** [review]

**Comment by AntonNeviarouski** [comment]
QA verified

**Pull request merged**
